"""Watch-listing status constants."""

LISTING_STATUS_PENDING_DIGEST = "pending_digest"
LISTING_STATUS_SENT = "sent"
LISTING_STATUS_EXCLUDED = "excluded"
LISTING_STATUS_DISMISSED = "dismissed"
LISTING_STATUS_SAVED = "saved"
LISTING_STATUS_NOT_RELEVANT = "not_relevant"
LISTING_STATUS_CONTACTED = "contacted"
LISTING_STATUS_STARRED = "starred"
LISTING_STATUS_INACTIVE = "inactive"

DELIVERABLE_LISTING_STATUSES = {LISTING_STATUS_PENDING_DIGEST}
VISIBLE_LISTING_STATUSES = {
    LISTING_STATUS_PENDING_DIGEST,
    LISTING_STATUS_SENT,
    LISTING_STATUS_SAVED,
    LISTING_STATUS_CONTACTED,
    LISTING_STATUS_STARRED,
}
USER_SETTABLE_LISTING_STATUSES = {
    LISTING_STATUS_STARRED,
    LISTING_STATUS_INACTIVE,
}
